### ISSUE TITLE
[Feature Request ] Allow selecting which type of commit must be included in releases notes

### ISSUE THREAD

**Issue by tinesoft** [low205/gradle-semantic-release-plugin#3]
Hi,

Thanks for this great plugin!

Would be great if we could configure which type of commits should be included in the release notes. 

Currently all of them (even technical tasks like **chore** and **style**) are included. Which is weird, causes generally only **feat**, **fix** and commits mentioning **BREAKING CHANGES**, [are included](https://github.com/semantic-release/semantic-release#commit-message-format) in the release notes.

**Comment by tinesoft** [comment]
It seems that **chore** and **style** (and other "technical" commit types) are no longer included as individual sections in the release notes (starting from v1.0.0) 👍. But still, would be great if we could choose to add them or not.

Maybe via a `includeCommitTypes` property in `SemanticReleasePluginExtension`? Its default value would be **["feat", "fix"]** (list of strings or list of entries of an enum named `CommitType` referring to those commit types)

what do you think?

**Comment by low205** [comment]
Hi. Glad you found this plugin useful. 

You should be able to control release changes with this configuration

```
import de.maltsev.gradle.semanticrelease.versions.VersionChangeGroup
semanticRelease {
    releaseChanges.set(listOf(VersionChangeGroup.MAJOR, VersionChangeGroup.MINOR, VersionChangeGroup.PATCH))
}
```
I am thinking to change this to be default one.

**Comment by low205** [comment]
Reopen, if the issue is not fixed.
