### ISSUE TITLE
[Question] how to use this plugin to release a multi-module project?

### ISSUE THREAD

**Issue by tinesoft** [low205/gradle-semantic-release-plugin#4]
Hi,

I am struggling to release a [multi-module java library](https://github.com/tinesoft/spring-esdata-loader) using this plugin....

When applying the plugin to each sub-modules i want to publish (because each has a `Bintray ` publishing plugin applied to it), the `gradle-semantic-release-plugin` tries to generate Release Notes as well, causing a failure: See [Travis Log](https://travis-ci.org/tinesoft/spring-esdata-loader/builds/586016415)

Is there a way limit the generation/publishing of  Release Notes to the **root project only**, while keeping the version inference when applied to a sub-module?

**Comment by low205** [comment]
I think you can try run semanticReleasePublish task only on root as a workaround. Try to use `:semanticReleasePublish` I will fix  application of plugin to subprojects in couple of days. It should apply inferred version to all subprojects by design, but right now only applies to first level of subprojects.

**Comment by low205** [comment]
If you have only one level of subprojects, then only apply plugin on root.

**Comment by tinesoft** [comment]
Hi,

Thanks for the quick answer 👍 

I tried to apply to root project only (see [Travis Build #145](https://travis-ci.org/tinesoft/spring-esdata-loader/builds/586097913)), but then it cannot execute publishing tasks (in my case [publishPackageToBintray](https://github.com/tinesoft/spring-esdata-loader/blob/master/gradle/bintray.gradle) and [gitPublishPush](https://github.com/tinesoft/spring-esdata-loader/blob/master/gradle/ghpages.gradle))...

In fact, the `onlyIf` clause failed due to methods `hasNewSemanticVersion()`  and `isOnTargetBranch()` not being found (even when prefixing with `rootProject.` )

Any ideas?

Thanks

**Comment by low205** [comment]
I will check your case. But I see we use it similarly as you, and those methods works on subprojects(except we write gradle builds in kotlin). Generally plugin code should be in classpath. Add plugin to subproject without applying. Code will be on classpath, and you would be able to use helper functions. 
```
plugins {
    id("de.maltsev.gradle.semanticrelease") apply false
}
```

Or add it to dependencies in buildSrc/build.gradle, as we do. As long plugin classes ares in classpath of the build.

**Comment by tinesoft** [comment]
Hi again,

Thanks for digging into this with me :) 

i have already tried what you mentioned:

(_in root `build.gradle`_)
> plugins {
>     id("de.maltsev.gradle.semanticrelease") apply false
> }

and adding the plugin as dependencies in the [buildSrc/build.gradle](https://github.com/tinesoft/spring-esdata-loader/blob/master/buildSrc/build.gradle) (before that, gradle couldn't even resolve the import of the helper methods...)

**Comment by low205** [comment]
Can you try apply in root? And add in classpath with apply false in subprojects. 
Plus I strongly believe, that buildSrc should be written in Kotlin. But likely not. 
Maybe copy buildSrc/build.gradle.kts to your project, and leave there only semantic release dependencies. 
Well, I will try to dig your build, just need some time.

**Comment by tinesoft** [comment]
Hello again,

Ok i have  made some progress.

The `onlyIf ` no longer complains about `hasNewSemanticVersion()/isOnTargetBranch()` not being found on root project. Was in fact a syntax issue. As These methods are **Kotlin extensions** on the `org.gradle.api.Project` class, the correct way to call them in **Groovy/Java** is _statically_ via **hasNewSemanticVersion(rootProject)** and not ~rootProject.hasNewSemanticVersion()~  (Kotlin syntax).
 See [Travis Log #153](https://travis-ci.org/tinesoft/spring-esdata-loader/builds/586795192)

so (kotlin syntax):
```
import de.maltsev.gradle.semanticrelease.project.hasNewSemanticVersion
import de.maltsev.gradle.semanticrelease.project.isOnTargetBranch

tasks {
  "publishPackageToBintray" {
    onlyIf { project.rootProject.hasNewSemanticVersion() && project.rootProject.isOnTargetBranch() }
  }
}
```

should be replaced by (for groovy syntax): 
```

import static de.maltsev.gradle.semanticrelease.project.ExtKt.hasNewSemanticVersion
import static de.maltsev.gradle.semanticrelease.project.ExtKt.isOnTargetBranch

tasks {
  "publishPackageToBintray" {
    onlyIf { hasNewSemanticVersion(project.rootProject) && isOnTargetBranch(project.rootProject) }
  }
}

```


Now the **nebula.bintray** task runs successfully.

But i now have another issue with it because it is not publishing the updated version of my artifacts...

**Comment by low205** [comment]
Sorry, completely missed about groovy/java syntax, I will think about some groovy ways to do the same. The main idea behind those methods is a need to incapsulate check for extra properties. 

When plugin finds new commits which will change latest release, it should set extra property `semanticReleaseHasNewSemanticVesrion`. If you are on master branch it will also set `semanticReleaseIsOnTarget` extra property. It uses `findProperty` method of `Project` so should work on any level, as it will search in ancestors. So you can safely omit `rootProject`.

Plugin assumes master branch development, with feature branches. If you want to publish in bintray on feature branches, then remove isOnTargetBranch check. 

So if you have no feature or fix commits after latest release, it will not have new version, and if you are not on target branch(master by default), then your task will not run. 

Hope it will help you somewhat. I will be polishing plugin, so there will be not such issues. It is really great that you looked and pointed out these problems.

**Comment by tinesoft** [comment]
Hi @low205 ,

> When plugin finds new commits which will change latest release, it should set extra property semanticReleaseHasNewSemanticVesrion. If you are on master branch it will also set semanticReleaseIsOnTarget extra property. It uses findProperty method of Project so should work on any level, as it will search in ancestors. So you can safely omit rootProject.

I can confirm this does work. See my [Travis Log #160.](https://travis-ci.org/tinesoft/spring-esdata-loader/builds/586970960)...

> Plugin assumes master branch development, with feature branches. If you want to publish in bintray on feature branches, then remove isOnTargetBranch check.

This is intented. I only want to publish to  bintray when on target ("master") branch

> So if you have no feature or fix commits after latest release, it will not have new version, and if you are not on target branch(master by default), then your task will not run.

There are changes since last commit and plugin detects them correctly (see  [Travis Log #160.](https://travis-ci.org/tinesoft/spring-esdata-loader/builds/586970960)). I believe my problem lies with the way i configured  **nebula.bintray**, which is still uploading the previous version artifacts somehow...

> Hope it will help you somewhat. I will be polishing plugin, so there will be not such issues. It is really great that you looked and pointed out these problems.

Except those kotlin/groovy syntax gotchas to know, i think your plugin is working great. These are more _documentation_ issues, especially for people (like me 😄)  using Groovy instead of Kotlin to write their gradle builds.

**Comment by tinesoft** [comment]
Hurray!

I finally got the last part (publishing to bintray/maven) working! It turns out, i was using the wrong publishing task (`"publishPackageToBintray"` while should be default maven `"publish"` instead).

Anyway, everything works fine now!

Thanks for your help

**Comment by low205** [comment]
Cool. Nice to hear that everything worked for you. I then will plan improvements in the plugin based on your feedback. Good luck. Thank you for using this plugin.
